spring.application.name=mcporchestrator

spring.ai.mcp.server.name=mcporchestrator
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.port=8080

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini

spring.ai.mcp.client.enabled=false

logging.level.sevin.mcporchestrator=INFO
logging.level.org.springframework.ai=DEBUG
